Repository Dia218/webty-backend-kotlin, pull requests merged in 2025-02, with the labels that each got.

#2 refactor: Recommend 도메인 kotlin으로 변환
  build.gradle.kts
  src/main/java/org/team14/webty/common/dto/PageDto.java
  src/main/java/org/team14/webty/recommend/controller/RecommendController.java
  src/main/java/org/team14/webty/recommend/entity/Recommend.java
  src/main/java/org/team14/webty/recommend/enumerate/LikeType.java
  src/main/java/org/team14/webty/recommend/repository/RecommendRepository.java
  src/main/java/org/team14/webty/recommend/service/RecommendService.java
  src/main/java/org/team14/webty/security/authentication/WebtyUserDetails.java
  src/main/java/org/team14/webty/user/entity/WebtyUser.java
  src/main/kotlin/org/team14/webty/recommend/controller/RecommendController.kt
  src/main/kotlin/org/team14/webty/recommend/entity/Recommend.kt
  src/main/kotlin/org/team14/webty/recommend/enumerate/LikeType.kt
  src/main/kotlin/org/team14/webty/recommend/repository/RecommendRepository.kt
  src/main/kotlin/org/team14/webty/recommend/service/RecommendService.kt
  src/test/kotlin/org/team14/webty/recommend/RecommendControllerTestKotlin.kt
Labels: domain-refactor, tests-passed

#10 fix 리뷰 병합후 오류 수정
  src/main/kotlin/org/team14/webty/recommend/controller/RecommendController.kt
  src/main/kotlin/org/team14/webty/review/repository/ReviewRepository.kt
  src/main/kotlin/org/team14/webty/review/service/ReviewService.kt
  src/test/kotlin/org/team14/webty/recommend/RecommendControllerTestKotlin.kt
Labels: bugfix

#11 refactor ReviewService
  src/main/kotlin/org/team14/webty/review/service/ReviewService.kt
Labels: minor-refactor

#20 feat : Security Test Migration
  build.gradle.kts
  src/test/kotlin/org/team14/webty/security/authentication/CustomAuthenticationFilterTest.kt
  src/test/kotlin/org/team14/webty/security/oauth2/LoginSuccessHandlerTest.kt
  src/test/kotlin/org/team14/webty/security/oauth2/LogoutSuccessHandlerTest.kt
  src/test/kotlin/org/team14/webty/security/token/JwtManagerTest.kt
Labels: tests-passed

#30 feat: 기존 자바코드 Common 추가사항 반영 (review 제외)
  src/main/java/org/team14/webty/common/config/JpaConfig.java
  src/main/java/org/team14/webty/common/entity/BaseEntity.java
  src/main/java/org/team14/webty/reviewComment/entity/ReviewComment.java
Labels: new-feature

#17 refactor: Voting Test Migration
  src/main/java/org/team14/webty/voting/controller/SimilarController.java
  src/main/java/org/team14/webty/voting/controller/VoteController.java
  src/main/java/org/team14/webty/voting/dto/SimilarRequest.java
  src/main/java/org/team14/webty/voting/dto/SimilarResponse.java
  src/main/java/org/team14/webty/voting/dto/SimilarResponseRequest.java
  src/main/java/org/team14/webty/voting/dto/VoteRequest.java
  src/main/java/org/team14/webty/voting/entity/Similar.java
  src/main/java/org/team14/webty/voting/entity/Vote.java
  src/main/java/org/team14/webty/voting/enumerate/VoteType.java
  src/main/java/org/team14/webty/voting/mapper/SimilarMapper.java
  src/main/java/org/team14/webty/voting/mapper/VoteMapper.java
  src/main/java/org/team14/webty/voting/repository/SimilarRepository.java
  src/main/java/org/team14/webty/voting/repository/VoteRepository.java
  src/main/java/org/team14/webty/voting/service/SimilarService.java
  src/main/java/org/team14/webty/voting/service/VoteService.java
  src/main/kotlin/org/team14/webty/voting/controller/SimilarController.kt
  src/main/kotlin/org/team14/webty/voting/controller/VoteController.kt
  src/main/kotlin/org/team14/webty/voting/dto/SimilarRequest.kt
  src/main/kotlin/org/team14/webty/voting/dto/SimilarResponse.kt
  src/main/kotlin/org/team14/webty/voting/dto/SimilarResponseRequest.kt
  src/main/kotlin/org/team14/webty/voting/dto/VoteRequest.kt
  src/main/kotlin/org/team14/webty/voting/entity/Similar.kt
  src/main/kotlin/org/team14/webty/voting/entity/Vote.kt
  src/main/kotlin/org/team14/webty/voting/enums/VoteType.kt
  src/main/kotlin/org/team14/webty/voting/mapper/SimilarMapper.kt
  src/main/kotlin/org/team14/webty/voting/mapper/VoteMapper.kt
  src/main/kotlin/org/team14/webty/voting/repository/SimilarRepository.kt
  src/main/kotlin/org/team14/webty/voting/repository/VoteRepository.kt
  src/main/kotlin/org/team14/webty/voting/service/SimilarService.kt
  src/main/kotlin/org/team14/webty/voting/service/VoteService.kt
  src/test/kotlin/org/team14/webty/voting/SimilarControllerTest.kt
  src/test/kotlin/org/team14/webty/voting/VoteControllerTest.kt
  src/test/kotlin/org/team14/webty/voting/VotingTestDataInitializer.kt
Labels: tests-passed

#38 Refactor: Recommend
  src/main/kotlin/org/team14/webty/recommend/controller/RecommendController.kt
  src/main/kotlin/org/team14/webty/recommend/entity/Recommend.kt
  src/main/kotlin/org/team14/webty/recommend/repository/RecommendRepository.kt
  src/main/kotlin/org/team14/webty/recommend/service/RecommendService.kt
  src/test/kotlin/org/team14/webty/recommend/RecommendControllerTestKotlin.kt
Labels: domain-refactor, tests-passed

#39 refactor : Security Kotlin Migration
  src/main/java/org/team14/webty/security/authentication/AuthWebtyUserProvider.java
  src/main/java/org/team14/webty/security/authentication/CustomAuthenticationFilter.java
  src/main/java/org/team14/webty/security/authentication/WebtyUserDetails.java
  src/main/java/org/team14/webty/security/authentication/WebtyUserDetailsService.java
  src/main/java/org/team14/webty/security/config/RedisConfig.java
  src/main/java/org/team14/webty/security/config/SecurityConfig.java
  src/main/java/org/team14/webty/security/oauth2/LoginSuccessHandler.java
  src/main/java/org/team14/webty/security/oauth2/LogoutSuccessHandler.java
  src/main/java/org/team14/webty/security/oauth2/ProviderUserInfo.java
  src/main/java/org/team14/webty/security/policy/ExpirationPolicy.java
  src/main/java/org/team14/webty/security/token/JwtManager.java
  src/main/java/org/team14/webty/user/entity/WebtyUser.java
  src/main/kotlin/org/team14/webty/security/authentication/AuthWebtyUserProvider.kt
  src/main/kotlin/org/team14/webty/security/authentication/CustomAuthenticationFilter.kt
  src/main/kotlin/org/team14/webty/security/authentication/WebtyUserDetails.kt
  src/main/kotlin/org/team14/webty/security/authentication/WebtyUserDetailsService.kt
  src/main/kotlin/org/team14/webty/security/config/RedisConfig.kt
  src/main/kotlin/org/team14/webty/security/config/SecurityConfig.kt
  src/main/kotlin/org/team14/webty/security/oauth2/LoginSuccessHandler.kt
  src/main/kotlin/org/team14/webty/security/oauth2/LogoutSuccessHandler.kt
  src/main/kotlin/org/team14/webty/security/oauth2/ProviderUserInfo.kt
  src/main/kotlin/org/team14/webty/security/policy/ExpirationPolicy.kt
  src/main/kotlin/org/team14/webty/security/token/JwtManager.kt
  src/test/kotlin/org/team14/webty/security/authentication/CustomAuthenticationFilterTest.kt
  src/test/kotlin/org/team14/webty/security/oauth2/LoginSuccessHandlerTest.kt
Labels: domain-refactor, tests-passed

#40 Refactor/review/issue 36
  src/main/kotlin/org/team14/webty/review/entity/Review.kt
  src/main/kotlin/org/team14/webty/review/repository/ReviewRepository.kt
  src/main/kotlin/org/team14/webty/review/service/ReviewService.kt
Labels: minor-refactor, tests-passed

#44 Refactor: Voting Kotlin by mentoring
  src/main/kotlin/org/team14/webty/voting/dto/SimilarRequest.kt
  src/main/kotlin/org/team14/webty/voting/dto/SimilarResponse.kt
  src/main/kotlin/org/team14/webty/voting/dto/SimilarResponseRequest.kt
  src/main/kotlin/org/team14/webty/voting/dto/VoteRequest.kt
  src/main/kotlin/org/team14/webty/voting/entity/Similar.kt
  src/main/kotlin/org/team14/webty/voting/entity/Vote.kt
  src/main/kotlin/org/team14/webty/voting/service/VoteService.kt
Labels: domain-refactor, tests-passed

#51 refactor: User Migration
  src/main/java/org/team14/webty/reviewComment/mapper/ReviewCommentMapper.java
  src/main/java/org/team14/webty/user/controller/UserController.java
  src/main/java/org/team14/webty/user/dto/ImageResponse.java
  src/main/java/org/team14/webty/user/dto/NicknameRequest.java
  src/main/java/org/team14/webty/user/dto/NicknameResponse.java
  src/main/java/org/team14/webty/user/dto/UserDataResponse.java
  src/main/java/org/team14/webty/user/entity/SocialProvider.java
  src/main/java/org/team14/webty/user/entity/WebtyUser.java
  src/main/java/org/team14/webty/user/enumerate/SocialProviderType.java
  src/main/java/org/team14/webty/user/repository/SocialProviderRepository.java
  src/main/java/org/team14/webty/user/repository/UserRepository.java
  src/main/java/org/team14/webty/user/service/UserService.java
  src/main/kotlin/org/team14/webty/recommend/service/RecommendService.kt
  src/main/kotlin/org/team14/webty/review/mapper/ReviewMapper.kt
  src/main/kotlin/org/team14/webty/security/oauth2/LoginSuccessHandler.kt
  src/main/kotlin/org/team14/webty/user/controller/UserController.kt
  src/main/kotlin/org/team14/webty/user/dto/ImageResponse.kt
  src/main/kotlin/org/team14/webty/user/dto/NicknameRequest.kt
  src/main/kotlin/org/team14/webty/user/dto/NicknameResponse.kt
  src/main/kotlin/org/team14/webty/user/dto/UserDataResponse.kt
  src/main/kotlin/org/team14/webty/user/entity/SocialProvider.kt
  src/main/kotlin/org/team14/webty/user/entity/WebtyUser.kt
  src/main/kotlin/org/team14/webty/user/enums/SocialProviderType.kt
  src/main/kotlin/org/team14/webty/user/mapper/UserDataResponseMapper.kt
  src/main/kotlin/org/team14/webty/user/repository/SocialProviderRepository.kt
  src/main/kotlin/org/team14/webty/user/repository/UserRepository.kt
  src/main/kotlin/org/team14/webty/user/service/UserService.kt
  src/main/kotlin/org/team14/webty/voting/mapper/VoteMapper.kt
  src/main/kotlin/org/team14/webty/voting/service/SimilarService.kt
  src/main/kotlin/org/team14/webty/voting/service/VoteService.kt
  src/test/kotlin/org/team14/webty/recommend/RecommendControllerTestKotlin.kt
  src/test/kotlin/org/team14/webty/review/ReviewControllerTest.kt
  src/test/kotlin/org/team14/webty/security/oauth2/LoginSuccessHandlerTest.kt
  src/test/kotlin/org/team14/webty/security/token/JwtManagerTest.kt
  src/test/kotlin/org/team14/webty/user/UserControllerTest.kt
  src/test/kotlin/org/team14/webty/voting/SimilarControllerTest.kt
  src/test/kotlin/org/team14/webty/voting/VoteControllerTest.kt
  src/test/kotlin/org/team14/webty/voting/VotingTestDataInitializer.kt
  src/test/kotlin/org/team14/webty/webtoon/webtoonControllerTest.kt
Labels: domain-refactor, multiple-file-changes, global-refactor

#45 refactor: favorite webtoon 도메인+favorite webtoon 테스트 코드를 kolin으로 변환
  src/main/kotlin/org/team14/webty/webtoon/controller/FavoriteController.kt
  src/main/kotlin/org/team14/webty/webtoon/entity/Favorite.kt
  src/main/kotlin/org/team14/webty/webtoon/mapper/FavoriteMapper.kt
  src/main/kotlin/org/team14/webty/webtoon/repository/FavoriteRepository.kt
  src/main/kotlin/org/team14/webty/webtoon/service/FavoriteService.kt
  src/test/kotlin/org/team14/webty/webtoon/FavoriteControllerTest.kt
Labels: domain-refactor, tests-passed

#54 fix webtoon fetch error
  src/main/kotlin/org/team14/webty/webtoon/api/WebtoonApiResponse.kt
  src/main/kotlin/org/team14/webty/webtoon/mapper/WebtoonApiResponseMapper.kt
Labels: bugfix

#42 refactor: Migration of all
  src/main/java/org/team14/webty/reviewComment/controller/ReviewCommentController.java
  src/main/java/org/team14/webty/reviewComment/dto/CommentRequest.java
  src/main/java/org/team14/webty/reviewComment/dto/CommentResponse.java
  src/main/java/org/team14/webty/reviewComment/entity/ReviewComment.java
  src/main/java/org/team14/webty/reviewComment/mapper/ReviewCommentMapper.java
  src/main/java/org/team14/webty/reviewComment/repository/ReviewCommentRepository.java
  src/main/java/org/team14/webty/reviewComment/service/ReviewCommentService.java
  src/main/kotlin/org/team14/webty/reviewComment/controller/ReviewCommentController.kt
  src/main/kotlin/org/team14/webty/reviewComment/dto/CommentRequest.kt
  src/main/kotlin/org/team14/webty/reviewComment/dto/CommentResponse.kt
  src/main/kotlin/org/team14/webty/reviewComment/entity/ReviewComment.kt
  src/main/kotlin/org/team14/webty/reviewComment/mapper/ReviewCommentMapper.kt
  src/main/kotlin/org/team14/webty/reviewComment/repository/ReviewCommentRepository.kt
  src/main/kotlin/org/team14/webty/reviewComment/service/ReviewCommentService.kt
  src/test/kotlin/org/team14/webty/reviewComment/controller/ReviewCommentControllerTest.kt
Labels: domain-refactor

#58 fix: Compile Error
  src/main/kotlin/org/team14/webty/review/service/ReviewService.kt
  src/main/kotlin/org/team14/webty/reviewComment/mapper/ReviewCommentMapper.kt
  src/main/kotlin/org/team14/webty/reviewComment/service/ReviewCommentService.kt
Labels: hotfix

#59 Refactor:common migration
  src/main/java/org/team14/webty/common/config/JpaConfig.java
  src/main/java/org/team14/webty/common/config/RestTemplateConfig.java
  src/main/java/org/team14/webty/common/config/SchedulerConfig.java
  src/main/java/org/team14/webty/common/config/SwaggerConfig.java
  src/main/java/org/team14/webty/common/config/WebConfig.java
  src/main/java/org/team14/webty/common/cookies/CookieManager.java
  src/main/java/org/team14/webty/common/dto/PageDto.java
  src/main/java/org/team14/webty/common/entity/BaseEntity.java
  src/main/java/org/team14/webty/common/enums/TokenType.java
  src/main/java/org/team14/webty/common/exception/BusinessException.java
  src/main/java/org/team14/webty/common/exception/ErrorCode.java
  src/main/java/org/team14/webty/common/exception/ErrorDetails.java
  src/main/java/org/team14/webty/common/exception/GlobalExceptionHandler.java
  src/main/java/org/team14/webty/common/mapper/PageMapper.java
  src/main/java/org/team14/webty/common/util/FileStorageUtil.java
  src/main/kotlin/org/team14/webty/common/config/JpaConfig.kt
  src/main/kotlin/org/team14/webty/common/config/RestTemplateConfig.kt
  src/main/kotlin/org/team14/webty/common/config/SchedulerConfig.kt
  src/main/kotlin/org/team14/webty/common/config/SwaggerConfig.kt
  src/main/kotlin/org/team14/webty/common/config/WebConfig.kt
  src/main/kotlin/org/team14/webty/common/cookies/CookieManager.kt
  src/main/kotlin/org/team14/webty/common/dto/PageDto.kt
  src/main/kotlin/org/team14/webty/common/entity/BaseEntity.kt
  src/main/kotlin/org/team14/webty/common/enums/TokenType.kt
  src/main/kotlin/org/team14/webty/common/exception/BusinessException.kt
  src/main/kotlin/org/team14/webty/common/exception/ErrorCode.kt
  src/main/kotlin/org/team14/webty/common/exception/ErrorDetails.kt
  src/main/kotlin/org/team14/webty/common/exception/GlobalExceptionHandler.kt
  src/main/kotlin/org/team14/webty/common/mapper/PageMapper.kt
  src/main/kotlin/org/team14/webty/common/util/FileStorageUtil.kt
  src/main/kotlin/org/team14/webty/review/controller/ReviewController.kt
  src/main/kotlin/org/team14/webty/review/mapper/ReviewMapper.kt
  src/main/kotlin/org/team14/webty/reviewComment/mapper/ReviewCommentMapper.kt
  src/main/kotlin/org/team14/webty/user/entity/WebtyUser.kt
  src/main/kotlin/org/team14/webty/user/service/UserService.kt
Labels: domain-refactor

#63 fix:test error sorted out
  src/test/kotlin/org/team14/webty/reviewComment/controller/ReviewCommentControllerTest.kt
Labels: critical-bug

#66 fix: PageDTO isLast Error
  src/main/kotlin/org/team14/webty/common/dto/PageDto.kt
Labels: bugfix

#69 refactor: changing the property to be not allowed null
  src/main/kotlin/org/team14/webty/reviewComment/entity/ReviewComment.kt
Labels: execution-ok, minor-refactor

#67 fix: test case excution ok
  src/test/kotlin/org/team14/webty/reviewComment/controller/ReviewCommentControllerTest.kt
Labels: execution-ok

#78 refactor: VoteType Refactoring
  src/main/kotlin/org/team14/webty/common/exception/ErrorCode.kt
  src/main/kotlin/org/team14/webty/voting/enums/VoteType.kt
Labels: domain-refactor

#81 refactor: enumerate -> enums
  src/main/kotlin/org/team14/webty/recommend/entity/Recommend.kt
  src/main/kotlin/org/team14/webty/recommend/enums/LikeType.kt
  src/main/kotlin/org/team14/webty/recommend/repository/RecommendRepository.kt
  src/main/kotlin/org/team14/webty/recommend/service/RecommendService.kt
  src/main/kotlin/org/team14/webty/review/dto/ReviewDetailResponse.kt
  src/main/kotlin/org/team14/webty/review/dto/ReviewItemResponse.kt
  src/main/kotlin/org/team14/webty/review/dto/ReviewRequest.kt
  src/main/kotlin/org/team14/webty/review/entity/Review.kt
  src/main/kotlin/org/team14/webty/review/enums/SpoilerStatus.kt
  src/main/kotlin/org/team14/webty/webtoon/controller/WebtoonController.kt
  src/main/kotlin/org/team14/webty/webtoon/dto/WebtoonDetailDto.kt
  src/main/kotlin/org/team14/webty/webtoon/entity/Webtoon.kt
  src/main/kotlin/org/team14/webty/webtoon/enums/Platform.kt
  src/main/kotlin/org/team14/webty/webtoon/enums/WebtoonSort.kt
  src/main/kotlin/org/team14/webty/webtoon/mapper/WebtoonApiResponseMapper.kt
  src/main/kotlin/org/team14/webty/webtoon/repository/WebtoonRepository.kt
  src/main/kotlin/org/team14/webty/webtoon/service/WebtoonService.kt
  src/test/kotlin/org/team14/webty/recommend/RecommendControllerTestKotlin.kt
  src/test/kotlin/org/team14/webty/review/ReviewControllerTest.kt
  src/test/kotlin/org/team14/webty/reviewComment/controller/ReviewCommentControllerTest.kt
  src/test/kotlin/org/team14/webty/voting/VotingTestDataInitializer.kt
  src/test/kotlin/org/team14/webty/webtoon/FavoriteControllerTest.kt
  src/test/kotlin/org/team14/webty/webtoon/webtoonControllerTest.kt
Labels: execution-ok, multiple-file-changes, global-refactor, tests-passed

#87 Feat/voting/issue 86
  src/main/kotlin/org/team14/webty/common/redis/RedisPublisher.kt
  src/main/kotlin/org/team14/webty/common/redis/RedisSubscriber.kt
  src/main/kotlin/org/team14/webty/security/config/RedisConfig.kt
  src/main/kotlin/org/team14/webty/voting/controller/VoteController.kt
  src/main/kotlin/org/team14/webty/voting/dto/VoteRequest.kt
  src/main/kotlin/org/team14/webty/voting/repository/SimilarRepository.kt
  src/main/kotlin/org/team14/webty/voting/service/VoteService.kt
Labels: new-feature

#94 feat: RedisConfig security -> common & Add searchRedisTemplate
  src/main/kotlin/org/team14/webty/common/config/RedisConfig.kt
Labels: minor-refactor, common-feature

#96 refactor: VoteController, VoteService
  src/main/kotlin/org/team14/webty/common/redis/RedisSubscriber.kt
  src/main/kotlin/org/team14/webty/voting/cache/VoteCacheInitializer.kt
  src/main/kotlin/org/team14/webty/voting/cache/VoteCacheService.kt
  src/main/kotlin/org/team14/webty/voting/controller/VoteController.kt
  src/main/kotlin/org/team14/webty/voting/dto/SimilarResponse.kt
  src/main/kotlin/org/team14/webty/voting/dto/VoteRequest.kt
  src/main/kotlin/org/team14/webty/voting/mapper/SimilarMapper.kt
  src/main/kotlin/org/team14/webty/voting/service/SimilarService.kt
  src/main/kotlin/org/team14/webty/voting/service/VoteService.kt
Labels: minor-refactor

#91 feat: making the search domain by MySQL+Redis
  src/main/kotlin/org/team14/webty/common/config/JacksonConfig.kt
  src/main/kotlin/org/team14/webty/common/config/RedisConfig.kt
  src/main/kotlin/org/team14/webty/common/util/CompressionUtils.kt
  src/main/kotlin/org/team14/webty/search/constants/SearchConstants.kt
  src/main/kotlin/org/team14/webty/search/controller/SearchController.kt
  src/main/kotlin/org/team14/webty/search/dto/SearchResponseDto.kt
  src/main/kotlin/org/team14/webty/search/dto/SearchSuggestionDto.kt
  src/main/kotlin/org/team14/webty/search/dto/SuggestionItemDto.kt
  src/main/kotlin/org/team14/webty/search/enums/SearchType.kt
  src/main/kotlin/org/team14/webty/search/enums/SortType.kt
  src/main/kotlin/org/team14/webty/search/mapper/SearchRecommendMapper.kt
  src/main/kotlin/org/team14/webty/search/mapper/SearchResponseMapper.kt
  src/main/kotlin/org/team14/webty/search/mapper/SearchReviewMapper.kt
  src/main/kotlin/org/team14/webty/search/repository/SearchQueryBuilder.kt
  src/main/kotlin/org/team14/webty/search/repository/SearchRepository.kt
  src/main/kotlin/org/team14/webty/search/service/AutocompleteService.kt
  src/main/kotlin/org/team14/webty/search/service/SearchCacheService.kt
  src/main/kotlin/org/team14/webty/search/service/SearchExecutor.kt
  src/main/kotlin/org/team14/webty/search/service/SearchRequestProcessor.kt
  src/main/kotlin/org/team14/webty/search/service/SearchService.kt
  src/main/kotlin/org/team14/webty/search/service/SuggestionProcessor.kt
  src/main/kotlin/org/team14/webty/security/config/SecurityConfig.kt
Labels: common-feature

#100 chore guild.gradle.kts
  build.gradle.kts
Labels: dependency-update
