Repository Dia218/webty-backend-kotlin, pull requests merged in 2025-03, with the labels that each got.

#105 [refactor] review 조회 성능개선
  src/main/kotlin/org/team14/webty/review/dto/ReviewItemResponse.kt
  src/main/kotlin/org/team14/webty/review/mapper/ReviewMapper.kt
  src/main/kotlin/org/team14/webty/review/service/ReviewService.kt
  src/main/kotlin/org/team14/webty/reviewComment/entity/ReviewComment.kt
  src/main/kotlin/org/team14/webty/reviewComment/repository/ReviewCommentRepository.kt
  src/main/kotlin/org/team14/webty/search/mapper/SearchReviewMapper.kt
Labels: minor-refactor, improvement

#107 dependency: modification for execution coroutines
  build.gradle.kts
  src/main/kotlin/org/team14/webty/search/controller/SearchController.kt
  src/main/kotlin/org/team14/webty/search/repository/SearchQueryBuilder.kt
Labels: dependency-update

#111 Refactor Webtoon crawler 보완
  src/main/kotlin/org/team14/webty/webtoon/repository/WebtoonRepository.kt
  src/main/kotlin/org/team14/webty/webtoon/service/WebtoonService.kt
  src/main/resources/application-prod.yml
Labels: minor-refactor

#113 [Search] 조회수 정렬기능추가
  src/main/kotlin/org/team14/webty/search/repository/SearchRepository.kt
  src/main/kotlin/org/team14/webty/search/service/SearchRequestProcessor.kt
  src/main/kotlin/org/team14/webty/search/service/SearchService.kt
Labels: new-feature

#122 refactor: Add DockerCompose for Dev
  docker/webty-dev/docker-compose.dev.yml
Labels: execution-ok, improvement

#120 Feat/voting/issue 119
  src/main/kotlin/org/team14/webty/common/config/WebSocketConfig.kt
  src/main/kotlin/org/team14/webty/common/interceptor/WebSocketAuthInterceptor.kt
  src/main/kotlin/org/team14/webty/common/redis/RedisBatch.kt
  src/main/kotlin/org/team14/webty/voting/controller/VoteController.kt
  src/main/kotlin/org/team14/webty/voting/dto/SimilarResponse.kt
  src/main/kotlin/org/team14/webty/voting/dto/VoteStatusResponse.kt
  src/main/kotlin/org/team14/webty/voting/mapper/SimilarMapper.kt
  src/main/kotlin/org/team14/webty/voting/repository/VoteRepository.kt
  src/main/kotlin/org/team14/webty/voting/service/VoteService.kt
Labels: bugfix, new-feature, frontend-sync

#125 test: Fix K6-DockerCompose ElasticSearch Error & Change K6-Backend Port
  docker/Dockerfile
  docker/webty-k6/docker-compose.k6.yml
  src/main/kotlin/org/team14/webty/common/config/ElasticRestClientConfig.kt
  src/main/kotlin/org/team14/webty/security/config/SecurityConfig.kt
  src/main/resources/application-k6.yml
  src/main/resources/application-prod.yml
  src/main/resources/application-test.yml
  src/main/resources/docs/application.md
  src/test/k6/docker-compose.yml
  src/test/k6/voting/similar-initializer.js
  src/test/k6/voting/similar-test.js
  src/test/k6/voting/vote-test.js
  src/test/k6/voting/webtoon-initializer.js
Labels: execution-ok, rebuild, common-feature

#128 [search] 검색기능에서 캐싱기능 비활성화
  src/main/kotlin/org/team14/webty/search/constants/SearchConstants.kt
  src/main/kotlin/org/team14/webty/search/service/SearchCacheService.kt
  src/main/kotlin/org/team14/webty/search/service/SearchExecutor.kt
Labels: critical-bug

#131 refactor: Rename Redis Pub/Sub
  src/main/kotlin/org/team14/webty/common/config/RedisConfig.kt
  src/main/kotlin/org/team14/webty/voting/message/VotingMessagePublisher.kt
  src/main/kotlin/org/team14/webty/voting/message/VotingMessageSubscriber.kt
  src/main/kotlin/org/team14/webty/voting/service/VoteService.kt
Labels: minor-refactor

#133 refactor: Unuse AuthWebtyUserProvider
  src/main/kotlin/org/team14/webty/voting/controller/SimilarController.kt
  src/main/kotlin/org/team14/webty/voting/service/SimilarService.kt
Labels: domain-refactor

#137 fix: Application.md Error
  src/main/resources/docs/application.md
Labels: hotfix

#139 fix: similar-test.js 수정
  gradlew
  src/test/k6/voting/similar-test.js
Labels: bugfix

#135 develop: Review Redis Cache Merge 제안
  src/main/kotlin/org/team14/webty/review/cache/ViewCountCacheService.kt
  src/main/kotlin/org/team14/webty/review/controller/ReviewController.kt
  src/main/kotlin/org/team14/webty/review/mapper/ReviewMapper.kt
  src/main/kotlin/org/team14/webty/review/repository/ReviewRepository.kt
  src/main/kotlin/org/team14/webty/review/service/ReviewService.kt
Labels: execution-ok

#142 refactor Webtoon API crawler 향상
  build.gradle.kts
  src/main/kotlin/org/team14/webty/common/config/WebClientConfig.kt
  src/main/kotlin/org/team14/webty/webtoon/controller/WebtoonController.kt
  src/main/kotlin/org/team14/webty/webtoon/infrastructure/WebtoonApiWebClient.kt
  src/main/kotlin/org/team14/webty/webtoon/schedueler/WebtoonScheduler.kt
  src/main/kotlin/org/team14/webty/webtoon/service/WebtoonService.kt
Labels: minor-refactor

#147 [search] 초성검색기능, 자동완성 정밀도 설정코드(minMatchScore) 추가
  src/main/kotlin/org/team14/webty/search/constants/SearchConstants.kt
  src/main/kotlin/org/team14/webty/search/controller/SearchController.kt
  src/main/kotlin/org/team14/webty/search/service/AutocompleteService.kt
  src/main/kotlin/org/team14/webty/search/service/SuggestionProcessor.kt
Labels: new-feature

#152 refactor 조회수관련
  src/main/kotlin/org/team14/webty/review/cache/ViewCountCacheService.kt
  src/main/kotlin/org/team14/webty/review/mapper/ReviewMapper.kt
  src/main/kotlin/org/team14/webty/review/service/ReviewService.kt
  src/main/kotlin/org/team14/webty/search/mapper/SearchReviewMapper.kt
Labels: ui-ux

#155 chore: Write Readme
  README.md
Labels: docs-update
